language: php

php:
  - 7.0

before_install:
  - composer require php-coveralls/php-coveralls
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover ./tests/_reports/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v
